name: rtt
version: 0.1.0.0
github: "githubuser/rtt"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/rtt#readme>

dependencies:
  - base >= 4.7 && < 5
  - serth-serialiser
  - serth-json-parser
  - aeson
  - deepseq

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

benchmarks:
  rtt:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rtt
      - aeson
      - deepseq
      - servant
      - servant-server
      - warp
      - criterion
      - network-uri
      - HTTP
      - bytestring
      - flatparse
